name: udemx-services

services:

  nginx:
    image: nginx:1.28.0
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/ssl/udemx-debian/https.crt:/etc/nginx/ssl/https.crt:ro
      - /etc/ssl/udemx-debian/https.key:/etc/nginx/ssl/https.key:ro
      - /srv/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /srv/nginx/logs:/var/log/nginx
    depends_on:
      - jenkins
      - docker-registry
      - docker-registry-ui
    networks: [udemx-network]
    restart: unless-stopped

  mariadb:
    image: mariadb:11.4.7
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "Alma1234"
    ports:
      - "3306:3306"
    volumes:
      - /srv/mariadb:/var/lib/mysql
    networks: [udemx-network]
    restart: unless-stopped

  jenkins:
    image: jenkins/jenkins:2.511
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - /srv/jenkins:/var/jenkins_home
    networks: [udemx-network]
    restart: unless-stopped

  docker-registry:
    image: registry:3.0.0
    container_name: docker-registry
    environment:
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin: '["http://docker-registry-ui"]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods: '["HEAD", "GET", "OPTIONS", "DELETE"]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Credentials: '["true"]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers: '["Authorization", "Accept", "Cache-Control"]'
      REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers: '["Docker-Content-Digest"]'
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
    ports:
      - "5000:5000"
    volumes:
      - /srv/docker/registry:/var/lib/registry
    networks: [udemx-network]
    restart: unless-stopped

  docker-registry-ui:
    image: joxit/docker-registry-ui:main
    container_name: docker-registry-ui
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Docker Registry UI
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=http://docker-registry:5000
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=false
      - CATALOG_ELEMENTS_LIMIT=1000
    depends_on: [docker-registry]
    networks: [udemx-network]
    restart: unless-stopped

networks:
  udemx-network:
    external: true